/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/assets': RouteRecordInfo<
      '/assets',
      '/assets',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/audio': RouteRecordInfo<
      '/audio',
      '/audio',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/automacros': RouteRecordInfo<
      '/automacros',
      '/automacros',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/channelPoints': RouteRecordInfo<
      '/channelPoints',
      '/channelPoints',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/commands': RouteRecordInfo<
      '/commands',
      '/commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/connections': RouteRecordInfo<
      '/connections',
      '/connections',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/events': RouteRecordInfo<
      '/events',
      '/events',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games': RouteRecordInfo<
      '/games',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/gameScene': RouteRecordInfo<
      '/gameScene',
      '/gameScene',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/integrations': RouteRecordInfo<
      '/integrations',
      '/integrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/macros': RouteRecordInfo<
      '/macros',
      '/macros',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/music': RouteRecordInfo<
      '/music',
      '/music',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/obs': RouteRecordInfo<
      '/obs',
      '/obs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/overlay': RouteRecordInfo<
      '/overlay',
      '/overlay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/recovery': RouteRecordInfo<
      '/recovery',
      '/recovery',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rotatingscenes': RouteRecordInfo<
      '/rotatingscenes',
      '/rotatingscenes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/variables': RouteRecordInfo<
      '/variables',
      '/variables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/yolobox': RouteRecordInfo<
      '/yolobox',
      '/yolobox',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/assets.vue': {
      routes:
        | '/assets'
      views:
        | never
    }
    'src/pages/audio.vue': {
      routes:
        | '/audio'
      views:
        | never
    }
    'src/pages/automacros.vue': {
      routes:
        | '/automacros'
      views:
        | never
    }
    'src/pages/channelPoints.vue': {
      routes:
        | '/channelPoints'
      views:
        | never
    }
    'src/pages/commands.vue': {
      routes:
        | '/commands'
      views:
        | never
    }
    'src/pages/connections.vue': {
      routes:
        | '/connections'
      views:
        | never
    }
    'src/pages/events.vue': {
      routes:
        | '/events'
      views:
        | never
    }
    'src/pages/games.vue': {
      routes:
        | '/games'
      views:
        | never
    }
    'src/pages/gameScene.vue': {
      routes:
        | '/gameScene'
      views:
        | never
    }
    'src/pages/integrations.vue': {
      routes:
        | '/integrations'
      views:
        | never
    }
    'src/pages/macros.vue': {
      routes:
        | '/macros'
      views:
        | never
    }
    'src/pages/media.vue': {
      routes:
        | '/media'
      views:
        | never
    }
    'src/pages/music.vue': {
      routes:
        | '/music'
      views:
        | never
    }
    'src/pages/obs.vue': {
      routes:
        | '/obs'
      views:
        | never
    }
    'src/pages/overlay.vue': {
      routes:
        | '/overlay'
      views:
        | never
    }
    'src/pages/recovery.vue': {
      routes:
        | '/recovery'
      views:
        | never
    }
    'src/pages/rotatingscenes.vue': {
      routes:
        | '/rotatingscenes'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/variables.vue': {
      routes:
        | '/variables'
      views:
        | never
    }
    'src/pages/yolobox.vue': {
      routes:
        | '/yolobox'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
